# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    arthegas:
                        password: $2y$12$g2vK/04cDQfukYn8Xvbg9e5ndF/fcSRnXTcR3jTcIabPHrbw4WyN2
                        roles: 'ROLE_USER'
                    snipzer:
                        password: $2y$12$g2vK/04cDQfukYn8Xvbg9e5ndF/fcSRnXTcR3jTcIabPHrbw4WyN2
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            security: true
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }