parameters:
    #customer.speaker.name: 'Heisenberg'

services:

    customer.name_registry:
        class: CustomerBundle\Service\NameRegistry

    customer.speaker:
        class: CustomerBundle\Service\Speaker
        arguments: ['@customer.name_registry']

    customer.notifier:
        class: CustomerBundle\Service\Notifier
        arguments:
            - '@twig'
            - '@mailer'
            - '%recipient%'
    customer.balance_watcher:
        class: CustomerBundle\Service\BalanceWatcher
        arguments:
            - '@doctrine.orm.default_entity_manager'