AppBundle\Entity\Merchant:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MerchantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '64'
        code:
            type: string
            length: '6'
        feedUrl:
            type: string
            length: 255
    lifecycleCallbacks: {  }
