# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    snipzer:
                        password: $2y$12$02nC9CsjKO.Dwro4997s9e5cHAMgK5EgO2JFeQFxTwP3kr5CIZM5.
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$5tE6d281yYZKUPVU11Ak5uIa9A43mtn9PhgFTSjBG7VUP5jHJtfd6
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                default_target_path: app_admin_dashboard
                target_path_parameter: _target_path
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }